export const contactListClasses = 'relative flex flex-col border-[1px] border-gray-300 rounded-[8px] p-[16px] mb-[12px]'
export const commonClasses = "shadow-none focus:shadow-custom1 focus:border-[1px] focus:border-purple-300"
export const commonClasses2 = "text-md font-normal text-gray-900 focus:shadow-custom1 focus:border-[1px] focus:border-purple-300"
export const commonFontClasses = "text-sm font-medium text-gray-700"
export const requiredErrorClasses = "text-sm font-medium text-error-500"
export const selectFormMessageClasses = "pl-[44px] pb-[8px]"
export const preFilledClasses = "disabled:text-black-700 disabled:opacity-1"
export const disabledClasses = "bg-inherit "
export const commonFontClassesAddDialog = "text-md font-normal text-gray-900"
export const COMMON_TAB_CLASSES = "text-sm font-semibold py-[8px] px-[12px] cursor-pointer"
export const SELECTED_TAB_CLASSES = "bg-purple-100 rounded-[6px] text-purple-700 "
export const inputFormMessageClassesWithSelect = "ml-[-82px]"
export const tableHeaderClass = 'text-gray-600 text-xs font-medium px-[24px] py-[12px] bg-gray-50 border-b-[1px] border-gray-200 sticky top-0'
export const popoverSidesheetWidthClasses = 'xl:w-[29vw] 2xl:w-[calc(21vw+10px)]'
export const disabledSidebarItem = 'opacity-[0.3] cursor-not-allowed hover:cursor-not-allowed pointer-events-none'